version: "3.7"
x-labels:
  &default-labels
  br.com.lnls-sirius.department: ${DEPARTMENT}
  org.opencontainers.image.authors: ${AUTHOR}
  org.opencontainers.image.created: ${BUILD_DATE_RFC339}
  org.opencontainers.image.licenses: ${LICENSE}
  org.opencontainers.image.revision: ${COMMIT_HASH}
  org.opencontainers.image.source: ${REPOSITORY}
  org.opencontainers.image.url: ${REPOSITORY}
  org.opencontainers.image.vendor: ${VENDOR}
  org.opencontainers.image.version: ${COMMIT_HASH}-${BUILD_DATE}

services:
  etherip:
    build: .
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-base:${COMMIT_HASH}-${BUILD_DATE}

  rf-bo:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-bo:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: rf_bo
      labels:
        <<: *default-labels

  rf-si:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-si:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: rf_si
      labels:
        <<: *default-labels

  delta:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-delta:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: delta
      labels:
        <<: *default-labels

  fcplc01:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc01:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc01
      labels:
        <<: *default-labels

  fcplc02:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc02:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc02
      labels:
        <<: *default-labels

  fcplc03:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc03:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc03
      labels:
        <<: *default-labels

  linac:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidlinac:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: linac
      labels:
        <<: *default-labels

  petraV:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidpetra5:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: petraV
      labels:
        <<: *default-labels

  petraVII:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidpetra7:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: petraVII
      labels:
        <<: *default-labels

  delta_v2:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-delta-v2:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: delta_v2
      labels:
        <<: *default-labels
    environment:
      - TABLE_URL_COMMON="http://0.0.0.0/example-constants/delta/mm2k-conv-tables"
      - FILE_LV="LV-example.txt"
      - FILE_LH="LH-example.txt"
      - FILE_CR="CR-example.txt"
      - FILE_CL="CL-example.txt"
