version: "3.7"
services:
  etherip:
    build: "."
    image: "lnlscon/etheripioc_base:v1.0"

  sirius:
    image: "lnlscon/etheripioc_sirius:v1.0"
    build:
      context: .
      dockerfile: Dockerfile
      target: sirius
