version: "3.7"
x-labels: &default-labels
  br.com.lnls-sirius.department: ${DEPARTMENT}
  org.opencontainers.image.authors: ${AUTHOR}
  org.opencontainers.image.created: ${BUILD_DATE_RFC339}
  org.opencontainers.image.licenses: ${LICENSE}
  org.opencontainers.image.revision: ${COMMIT_HASH}
  org.opencontainers.image.source: ${REPOSITORY}
  org.opencontainers.image.url: ${REPOSITORY}
  org.opencontainers.image.vendor: ${VENDOR}
  org.opencontainers.image.version: ${COMMIT_HASH}-${BUILD_DATE}

x-args: &default-build-args
  DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX}
  COMMIT_HASH: ${COMMIT_HASH}
  BUILD_DATE: ${BUILD_DATE}

services:
  etherip:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-base:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      labels:
        <<: *default-labels

  fcplc01:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc01:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc01
      labels:
        <<: *default-labels

  fcplc02:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc02:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc02
      labels:
        <<: *default-labels

  fcplc03:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc03:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc03
      labels:
        <<: *default-labels

