version: "3.7"
x-labels:
  &default-labels
  br.com.lnls-sirius.department: ${DEPARTMENT}
  org.opencontainers.image.authors: ${AUTHOR}
  org.opencontainers.image.created: ${BUILD_DATE_RFC339}
  org.opencontainers.image.licenses: ${LICENSE}
  org.opencontainers.image.revision: ${COMMIT_HASH}
  org.opencontainers.image.source: ${REPOSITORY}
  org.opencontainers.image.url: ${REPOSITORY}
  org.opencontainers.image.vendor: ${VENDOR}
  org.opencontainers.image.version: ${COMMIT_HASH}-${BUILD_DATE}


x-args: &args
  DOCKER_IMAGE_BASE: ${DOCKER_IMAGE_BASE}
  DOCKER_ETHERIP_BASE_IMAGE: ${DOCKER_ETHERIP_BASE_IMAGE}

services:
  etherip:
    image: ${DOCKER_ETHERIP_BASE_IMAGE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      target: base

  rf-bo:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-bo:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile.ioc
      target: rf_bo

  rf-si:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-si:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: rf_si

  delta:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-delta:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: delta

  fcplc01:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc01:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: fcplc01

  fcplc02:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc02:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: fcplc02

  fcplc03:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc03:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: fcplc03

  linac:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidlinac:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: linac

  petraV:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidpetra5:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: petraV

  petraVII:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidpetra7:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: petraVII

  delta_v2:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-delta-v2:${COMMIT_HASH}-${BUILD_DATE}
    build:
      args:
        <<: *args
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: delta_v2
    environment:
      - TABLE_URL_COMMON="http://0.0.0.0/example-constants/delta/mm2k-conv-tables"
      - FILE_LV="LV-example.txt"
      - FILE_LH="LH-example.txt"
      - FILE_CR="CR-example.txt"
      - FILE_CL="CL-example.txt"
