version: "3.7"
services:
  etherip:
    build: "."
    image: "dockerregistry.lnls-sirius.com.br/gco/etheripioc_base:v1.3"

  rf_bo:
    image: "dockerregistry.lnls-sirius.com.br/gco/etheripioc_rf_bo:v1.5"
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      target: rf_bo

  rf_si:
    image: "dockerregistry.lnls-sirius.com.br/gco/etheripioc_rf_si:v1.5"
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
      target: rf_si
