version: "3.7"
x-labels: &default-labels
  br.com.lnls-sirius.department: ${DEPARTMENT}
  org.opencontainers.image.authors: ${AUTHOR}
  org.opencontainers.image.created: ${BUILD_DATE_RFC339}
  org.opencontainers.image.licenses: ${LICENSE}
  org.opencontainers.image.revision: ${COMMIT_HASH}
  org.opencontainers.image.source: ${REPOSITORY}
  org.opencontainers.image.url: ${REPOSITORY}
  org.opencontainers.image.vendor: ${VENDOR}
  org.opencontainers.image.version: ${COMMIT_HASH}-${BUILD_DATE}

x-args: &default-build-args
  DOCKER_IMAGE_PREFIX: ${DOCKER_IMAGE_PREFIX}
  COMMIT_HASH: ${COMMIT_HASH}
  BUILD_DATE: ${BUILD_DATE}

services:
  etherip:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-base:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: base
      labels:
        <<: *default-labels

  rf-bo:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-bo:${COMMIT_HASH}-${BUILD_DATE}
    build:
      labels:
        <<: *default-labels
      context: .
      dockerfile: Dockerfile
      target: rf-bo

  rf-si:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-si:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: rf-si

  delta:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-delta:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: DockerfileCas
      target: delta
      labels:
        <<: *default-labels

  fcplc01:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc01:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc01
      labels:
        <<: *default-labels

  fcplc02:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc02:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc02
      labels:
        <<: *default-labels

  fcplc03:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-fcplc03:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: fcplc03
      labels:
        <<: *default-labels

  linacskid:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidlinac:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: linacskid
      labels:
        <<: *default-labels

  p5skid:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidpetra5:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: p5skid
      labels:
        <<: *default-labels

  p7skid:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-skidpetra7:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: p7skid
      labels:
        <<: *default-labels

  rf-ssamp-tower-3:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-ssamp-tower-3:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: rf-ssamp-tower-3
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: ${AUTOSAVE_VOLUME_SOURCE}
        target: /opt/etheripIOC/autosave/save

  rf-ssamp-tower-4:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-ssamp-tower-4:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: rf-ssamp-tower-4
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: ${AUTOSAVE_VOLUME_SOURCE}
        target: /opt/etheripIOC/autosave/save

  rf-ssamp-tower-3-4:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-rf-ssamp-tower-3-4:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: rf-ssamp-tower-3-4
    network_mode: "host"
    restart: always
    volumes:
      - type: bind
        source: ${AUTOSAVE_VOLUME_SOURCE}
        target: /opt/etheripIOC/autosave/save

  delta_v2:
    image: ${DOCKER_IMAGE_PREFIX}/etheripioc-delta-v2:${COMMIT_HASH}-${BUILD_DATE}
    build:
      context: .
      dockerfile: Dockerfile
      target: delta_v2
      labels:
        <<: *default-labels
    environment:
      - TABLE_URL_COMMON="http://0.0.0.0/example-constants/delta/mm2k-conv-tables"
      - FILE_LV="LV-example.txt"
      - FILE_LH="LH-example.txt"
      - FILE_CR="CR-example.txt"
      - FILE_CL="CL-example.txt"
