#!/bin/sh
set -exu

DOCKER_REGISTRY=dockerregistry.lnls-sirius.com.br
DOCKER_USER_GROUP=gas
DOCKER_IMAGE_PREFIX=${DOCKER_REGISTRY}/${DOCKER_USER_GROUP}
DOCKER_IMAGE_BASE=debian:11-slim

AUTHOR="Claudio F. Carneiro <claudiofcarneiro@hotmail.com>"
BRANCH=$(git branch --no-color --show-current)
BUILD_DATE=$(date -I)
BUILD_DATE_RFC339=$(date --rfc-3339=seconds)
COMMIT=$(git rev-parse --short HEAD)
DEPARTMENT=GAS
REPOSITORY=$(git remote show origin |grep Fetch|awk '{ print $3 }')
VENDOR="CNPEM"

cat << EOF > .env
# Generic
DOCKER_REGISTRY=${DOCKER_REGISTRY}
DOCKER_USER_GROUP=${DOCKER_USER_GROUP}

AUTHOR=${AUTHOR}
BRANCH=${BRANCH}
BUILD_DATE=${BUILD_DATE}
BUILD_DATE_RFC339=${BUILD_DATE_RFC339}
COMMIT=${COMMIT}
DEPARTMENT=${DEPARTMENT}
REPOSITORY=${REPOSITORY}
VENDOR=${VENDOR}

# IOC
DOCKER_ETHERIP_BASE_IMAGE=${DOCKER_IMAGE_PREFIX}/etheripioc-base:${COMMIT_HASH}-${BUILD_DATE}
DOCKER_IMAGE_PREFIX=${DOCKER_IMAGE_PREFIX}
DOCKER_IMAGE_BASE=${DOCKER_IMAGE_BASE}
EOF
